In [62]:
import pandas as pd
import numpy as np
import math

In [63]:
data = pd.read_csv('2020_day3.csv', header=None, names=['row'])
data = data.apply(lambda x: [y for y in x.row], result_type='expand', axis=1)
data = data.replace('.', 0)
data = data.replace('#', 1)
data = data.to_numpy()
print(data)

[[0 0 0 ... 1 1 0]
 [0 1 0 ... 1 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 1 0]]


In [64]:
width = data.shape[0] * 3 + 1
repeat = math.ceil(width / data.shape[1])
tiled = np.tile(data, (1, repeat))
print(repeat)

32


In [65]:
tree_cnt = 0
x = 3
for i in range(1, tiled.shape[0]):
    # print(tiled[i][x])
    tree_cnt += tiled[i][x]
    x += 3

In [66]:
print(tree_cnt)

167
