In [16]:
import pandas as pd
import numpy as np
import math

In [17]:
data = pd.read_csv('2020_day3.csv', header=None, names=['row'])
data = data.apply(lambda x: [y for y in x.row], result_type='expand', axis=1)
data = data.replace('.', 0)
data = data.replace('#', 1)
data = data.to_numpy()
print(data)
print(data.shape)

[[0 0 0 ... 1 1 0]
 [0 1 0 ... 1 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 1 0]]
(323, 31)


In [18]:
width = data.shape[0] * 7 + 1
repeat = math.ceil(width / data.shape[1])
tiled = np.tile(data, (1, repeat))
print(repeat)

73


In [19]:
def get_trees(right, down):
    tree_cnt = 0
    x = right
    for i in range(down, tiled.shape[0], down):
        # print(tiled[i][x])
        tree_cnt += tiled[i][x]
        x += right
    return tree_cnt

In [20]:
print(get_trees(1, 1))
print(get_trees(3, 1))
print(get_trees(5, 1))
print(get_trees(7, 1))
print(get_trees(1, 2))

53
167
54
67
23


In [21]:
get_trees(1, 1) * get_trees(3, 1) * get_trees(5, 1) * get_trees(7, 1) * get_trees(1, 2)

736527114