In [41]:
import pandas as pd
import numpy as np

In [42]:
df = pd.read_csv('2021_day9.csv', header=None, names=['raw'])
df = df['raw'].astype(str).str.split('', expand=True)
df[0] = 10
df[len(df.columns)-1] = 10
df = df.astype(int)
wall = pd.DataFrame([[10 for x in range(len(df.columns))]])
df = pd.concat([wall, df, wall])
df.head()

0    1    2    3    4    5    6    7    8    9    ...  92   93   94   95   \
0   10   10   10   10   10   10   10   10   10   10  ...   10   10   10   10   
0   10    7    8    5    7    6    7    9    8    7  ...    4    3    4    9   
1   10    6    7    4    6    5    6    7    9    8  ...    9    4    9    8   
2   10    5    4    3    4    4    5    8    9    9  ...    9    9    8    7   
3   10    4    5    2    3    3    4    7    9    9  ...    9    8    7    6   

   96   97   98   99   100  101  
0   10   10   10   10   10   10  
0    5    4    3    4    5   10  
1    9    3    2    3    3   10  
2    8    9    1    0    2   10  
3    7    8    9    1    3   10  

[5 rows x 102 columns]

In [43]:
n = df.to_numpy()

In [44]:
low_points = []
for i in range(2,len(n)):
    for j in range(2,len(n[0])):
        v = n[i-1:i,j-1:j].sum()
        u = n[i-2:i-1,j-1:j].sum()
        d = n[i:i+1,j-1:j].sum()
        l = n[i-1:i,j-2:j-1].sum()
        r = n[i-1:i,j:j+1].sum()
        if v < u and v < d and v < l and v < r:
            low_points.append([i-1,j-1])
print(low_points)

[[1, 12], [1, 35], [1, 70], [1, 77], [1, 85], [1, 93], [2, 20], [2, 31], [2, 57], [3, 43], [3, 99], [4, 91], [5, 4], [5, 27], [5, 64], [6, 50], [6, 57], [6, 80], [6, 95], [7, 13], [7, 33], [7, 72], [7, 84], [8, 46], [8, 87], [9, 42], [9, 90], [9, 100], [10, 19], [10, 30], [11, 4], [11, 51], [12, 89], [13, 10], [13, 82], [14, 68], [15, 15], [15, 34], [15, 45], [15, 94], [16, 12], [16, 25], [16, 59], [16, 73], [18, 40], [18, 52], [19, 2], [20, 21], [20, 98], [21, 14], [21, 90], [22, 39], [22, 47], [22, 74], [22, 79], [23, 8], [23, 68], [24, 15], [24, 54], [24, 60], [25, 1], [25, 26], [25, 34], [25, 43], [25, 84], [26, 93], [27, 21], [28, 81], [28, 99], [29, 57], [30, 38], [30, 85], [30, 90], [30, 97], [31, 51], [32, 64], [32, 75], [33, 1], [33, 9], [33, 28], [33, 81], [33, 100], [34, 87], [35, 43], [36, 3], [36, 99], [37, 15], [37, 35], [37, 57], [37, 69], [37, 91], [39, 22], [39, 80], [40, 28], [40, 51], [42, 2], [42, 28], [42, 47], [42, 75], [42, 94], [43, 61], [44, 11], [44, 16], [44,

In [45]:
b = np.where((n == 9) | (n == 10), 0, 1)
print(b)
sizes = []
for l in low_points:
    to_explore = [l]
    size = 0
    while len(to_explore) > 0:
        i = to_explore.pop()
        if b[i[0], i[1]] == 1:
            size += 1
        u = b[i[0]-1, i[1]].sum()
        d = b[i[0]+1, i[1]].sum()
        l = b[i[0], i[1]-1].sum()
        r = b[i[0], i[1]+1].sum()
        b[i[0], i[1]] = 0
        if u == 1:
            to_explore.append([i[0]-1, i[1]])
        if d == 1:
            to_explore.append([i[0]+1, i[1]])
        if l == 1:
            to_explore.append([i[0], i[1]-1])
        if r == 1:
            to_explore.append([i[0], i[1]+1])
        # size += u + d + l + r
    sizes.append(size)
sizes.sort(reverse=True)
x = np.array(sizes[:3])
print(x)
print(x.prod())

[[0 0 0 ... 0 0 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 0 1 0]
 [0 1 1 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
[109 103 100]
1122700
