In [1]:
import pandas as pd
import numpy as np
from collections import Counter

In [66]:
n = np.genfromtxt('2021_day15_sample2.csv', delimiter=1)
n[0, 0] = 0
n

array([[0., 2., 4., 3.],
       [3., 5., 7., 3.],
       [6., 8., 9., 3.],
       [3., 3., 3., 1.]])

In [68]:
w = len(n.diagonal()) * 2
for i in range(-len(n)+1, len(n)):
    print(np.fliplr(n).diagonal(offset=-i))

[0.]
[2. 3.]
[4. 5. 6.]
[3. 7. 8. 3.]
[3. 9. 3.]
[3. 3.]
[1.]


In [ ]:
w = len(n.diagonal()) * 2
r = np.array
for i in range(-len(n)+1, len(n)):
    d = np.fliplr(n).diagonal(offset=-i)
    r = np.column_stack
    print(np.fliplr(n).diagonal(offset=-i))

In [50]:
w = len(n.diagonal())
w

3

In [70]:
w = 8
for i in range(-len(n)+1, len(n)):
    d = np.fliplr(n).diagonal(offset=-i)
    if len(d)*2 == w:
        print(np.concatenate([[d[0]], np.tile(d[1:-1], int(w-2)), [d[-1]]]))
    else:
        print(np.tile(d, int(w/len(d))))

[0. 0. 0. 0. 0. 0. 0. 0.]
[2. 3. 2. 3. 2. 3. 2. 3.]
[4. 5. 6. 4. 5. 6.]
[3. 7. 8. 7. 8. 7. 8. 7. 8. 7. 8. 7. 8. 3.]
[3. 9. 3. 3. 9. 3.]
[3. 3. 3. 3. 3. 3. 3. 3.]
[1. 1. 1. 1. 1. 1. 1. 1.]


In [35]:
print(n[1:,0])
print(n[1:,0].sum())

[1. 2. 3. 7. 1. 1. 3. 1. 2.]
21.0


In [36]:
print(n[0,1:])
print(n[0,1:].sum())

[1. 6. 3. 7. 5. 1. 7. 4. 2.]
36.0


In [37]:
print(n[2:,0])
print(n[2:,0].sum())

[2. 3. 7. 1. 1. 3. 1. 2.]
20.0


In [39]:
print(n[1,1:])
print(n[1,1:].sum())

[3. 8. 1. 3. 7. 3. 6. 7. 2.]
40.0


In [42]:
print(n[3:,0])
print(n[3:,0].sum() / 7)

[3. 7. 1. 1. 3. 1. 2.]
2.5714285714285716


In [43]:
print(n[2,1:])
print(n[2,1:].sum() / 9)

[1. 3. 6. 5. 1. 1. 3. 2. 8.]
3.3333333333333335


In [8]:
x = n.cumsum(axis=1)
x

array([[ 0.,  1.,  7., 10., 17., 22., 23., 30., 34., 36.],
       [ 1.,  4., 12., 13., 16., 23., 26., 32., 39., 41.],
       [ 2.,  3.,  6., 12., 17., 18., 19., 22., 24., 32.],
       [ 3.,  9., 18., 22., 31., 34., 35., 40., 46., 55.],
       [ 7., 11., 17., 20., 24., 25., 32., 33., 34., 35.],
       [ 1.,  4.,  5., 14., 15., 17., 25., 26., 29., 36.],
       [ 1.,  4.,  9., 18., 27., 28., 30., 34., 36., 37.],
       [ 3.,  4.,  6., 11., 15., 17., 18., 24., 27., 36.],
       [ 1.,  3., 12., 15., 16., 19., 27., 32., 34., 35.],
       [ 2.,  5.,  6.,  7., 16., 20., 24., 29., 37., 38.]])

In [9]:
y = n.cumsum(axis=0)
y

array([[ 0.,  1.,  6.,  3.,  7.,  5.,  1.,  7.,  4.,  2.],
       [ 1.,  4., 14.,  4., 10., 12.,  4., 13., 11.,  4.],
       [ 3.,  5., 17., 10., 15., 13.,  5., 16., 13., 12.],
       [ 6., 11., 26., 14., 24., 16.,  6., 21., 19., 21.],
       [13., 15., 32., 17., 28., 17., 13., 22., 20., 22.],
       [14., 18., 33., 26., 29., 19., 21., 23., 23., 29.],
       [15., 21., 38., 35., 38., 20., 23., 27., 25., 30.],
       [18., 22., 40., 40., 42., 22., 24., 33., 28., 39.],
       [19., 24., 49., 43., 43., 25., 32., 38., 30., 40.],
       [21., 27., 50., 44., 52., 29., 36., 43., 38., 41.]])

In [10]:
t = x + y
t

array([[ 0.,  2., 13., 13., 24., 27., 24., 37., 38., 38.],
       [ 2.,  8., 26., 17., 26., 35., 30., 45., 50., 45.],
       [ 5.,  8., 23., 22., 32., 31., 24., 38., 37., 44.],
       [ 9., 20., 44., 36., 55., 50., 41., 61., 65., 76.],
       [20., 26., 49., 37., 52., 42., 45., 55., 54., 57.],
       [15., 22., 38., 40., 44., 36., 46., 49., 52., 65.],
       [16., 25., 47., 53., 65., 48., 53., 61., 61., 67.],
       [21., 26., 46., 51., 57., 39., 42., 57., 55., 75.],
       [20., 27., 61., 58., 59., 44., 59., 70., 64., 75.],
       [23., 32., 56., 51., 68., 49., 60., 72., 75., 79.]])