In [32]:
import numpy as np
import pandas as pd

In [33]:
# df = pd.read_csv('2022_day8_sample.csv', header=None)
df = pd.read_csv('2022_day8.csv', header=None)
na = df[0].astype(str).str.split('', expand=True).to_numpy()[:,1:-1].astype(int)
print(na)

[[2 0 2 ... 3 0 0]
 [2 1 2 ... 1 1 0]
 [3 3 2 ... 2 0 1]
 ...
 [2 0 1 ... 0 3 3]
 [0 3 0 ... 1 0 1]
 [3 0 1 ... 1 3 3]]


In [34]:
res = np.ones(na.shape)
res[1:-1, 1:-1] = 0
print(res)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 1.]
 ...
 [1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [35]:
for x in range(na.shape[0])[1:-1]:
    for y in range(na.shape[1])[1:-1]:
        res[x,y] = na[x,y] > min([max(na[x,:y]), max(na[x,y+1:]), max(na[:x,y]), max(na[x+1:,y])])

In [36]:
print(res.sum())
print(res)

1669.0
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 0. ... 0. 1. 1.]
 [1. 1. 0. ... 1. 0. 1.]
 ...
 [1. 0. 0. ... 0. 0. 1.]
 [1. 1. 0. ... 0. 0. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
