In [7]:
import numpy as np
import pandas as pd

In [8]:
# df = pd.read_csv('2022_day8_sample.csv', header=None)
df = pd.read_csv('2022_day8.csv', header=None)
na = df[0].astype(str).str.split('', expand=True).to_numpy()[:,1:-1].astype(int)
print(na)

[[2 0 2 ... 3 0 0]
 [2 1 2 ... 1 1 0]
 [3 3 2 ... 2 0 1]
 ...
 [2 0 1 ... 0 3 3]
 [0 3 0 ... 1 0 1]
 [3 0 1 ... 1 3 3]]


In [9]:
res = np.zeros(na.shape)
print(res)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [10]:
for x in range(na.shape[0])[1:-1]:
    for y in range(na.shape[1])[1:-1]:
        l = na[x,:y][::-1]
        r = na[x,y+1:]
        u = na[:x,y][::-1]
        d = na[x+1:,y]
        lz = np.nonzero(l >= na[x,y])[0]
        rz = np.nonzero(r >= na[x,y])[0]
        uz = np.nonzero(u >= na[x,y])[0]
        dz = np.nonzero(d >= na[x,y])[0]
        if len(lz) == 0:
            ls = len(l)
        else:
            ls = lz.min() + 1
        if len(rz) == 0:
            rs = len(r)
        else:
            rs = rz.min() + 1
        if len(uz) == 0:
            us = len(u)
        else:
            us = uz.min() + 1
        if len(dz) == 0:
            ds = len(d)
        else:
            ds = dz.min() + 1
        res[x,y] = ls * rs * ds * us

In [11]:
print(res.max())
print(res)

331344.0
[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  1.  2. ...  1.  2.  0.]
 [ 0. 84. 20. ... 16.  1.  0.]
 ...
 [ 0.  1.  8. ...  1.  4.  0.]
 [ 0.  9.  1. ...  4.  1.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]
