In [47]:
import pandas as pd
import numpy as np

In [48]:
with open('2021_day4.csv', 'r') as f:
    l = f.readlines()
draw = np.array([int(x) for x in l[0].split(',')])
print(draw)


[30 35  8  2 39 37 72  7 81 41 25 46 56 18 89 70  0 15 84 75 88 67 42 44
 94 71 79 65 58 52 96 83 54 29 14 95 66 61 97 68 57 90 55 32 17 47 20 98
  1 69 63 62 31 86 77 85 87 93 26 40 24 19 48 76 73 49 34 45 82 22 80 78
 23  6 59 91 64 43 21 51 13  3 53 99  4 28 33 74 12  9 36 50 60 11 27 10
  5 16 92 38]


In [49]:
boards = []
n = []
for a in l[2:]:
    if a == '\n':
        boards.append(np.array(n))
        n = []
    else:
        r = [int(x) for x in a.replace('  ',' ').strip().split(' ')]
        n.append(r)
boards.append(np.array(n))

print(boards[0])
print(boards[1])
print(boards[2])


[[94 97 41 22 48]
 [21 47 72 23 26]
 [12 81 86 24 91]
 [71 78 90 59 54]
 [92 63 68 65  1]]
[[75 62 66 74 37]
 [14 79 35 96 30]
 [33 25 29 57  6]
 [60 93 17 55 53]
 [65 16 59 40 27]]
[[26 60 95 24 78]
 [55 12 22 68 43]
 [67 48 85 66 36]
 [29 80 52  3 56]
 [11 59 41 15 18]]


In [50]:
t = None
last = None
for d in draw:
    if t is not None:
        break
    for i in range(len(boards)):
        boards[i] = np.where(boards[i] == d, -1, boards[i])
        c = np.concatenate([boards[i].sum(axis=1), boards[i].sum(axis=0)])
        if -5 in c:
            t = np.where(boards[i] == -1, 0, boards[i]).sum()
            last = d
print(t, last)
print(t * last)
# print(boards)

835 65
54275


In [22]:
b = boards[0].copy()
print(b)
b = np.where(b == 9, -1, b)
print(b)

[[22 13 17 11  0]
 [ 8  2 23  4 24]
 [21  9 14 16  7]
 [ 6 10  3 18  5]
 [ 1 12 20 15 19]]
[[22 13 17 11  0]
 [ 8  2 23  4 24]
 [21 -1 14 16  7]
 [ 6 10  3 18  5]
 [ 1 12 20 15 19]]


In [25]:
b = boards[0].copy()
print(b)
print(b.sum(axis=1))
print(b.sum(axis=0))
print(np.concatenate([b.sum(axis=1), b.sum(axis=0)]))

[[22 13 17 11  0]
 [ 8  2 23  4 24]
 [21  9 14 16  7]
 [ 6 10  3 18  5]
 [ 1 12 20 15 19]]
[63 61 67 42 67]
[58 46 77 64 55]
[63 61 67 42 67 58 46 77 64 55]


In [30]:
b = boards[0].copy()
b = np.where(b == 8, -1, b)
b = np.where(b == 2, -1, b)
b = np.where(b == 23, -1, b)
b = np.where(b == 4, -1, b)
b = np.where(b == 24, -1, b)
print(b)
print(np.concatenate([b.sum(axis=1), b.sum(axis=0)]))
if -5 in np.concatenate([b.sum(axis=1), b.sum(axis=0)]):
    print(np.where(b == -1, 0, b).sum())

[[22 13 17 11  0]
 [-1 -1 -1 -1 -1]
 [21  9 14 16  7]
 [ 6 10  3 18  5]
 [ 1 12 20 15 19]]
[63 -5 67 42 67 49 43 53 59 30]
239
