In [2]:
import numpy as np
import pandas as pd
import csv

In [11]:
data = pd.read_csv('2020_day1.csv').to_numpy()
print(data)

[[1897]
 [1850]
 [1218]
 [1198]
 [1761]
 [1082]
 [1742]
 [1821]
 [1464]
 [1834]
 [1413]
 [1917]
 [1746]
 [1954]
 [1942]
 [1560]
 [1227]
 [1852]
 [1976]
 [1773]
 [1404]
 [1824]
 [1011]
 [1532]
 [1306]
 [1819]
 [1739]
 [1540]
 [1973]
 [1436]
 [1196]
 [1176]
 [1856]
 [1332]
 [1617]
 [1895]
 [1749]
 [1718]
 [1536]
 [1811]
 [ 113]
 [1008]
 [1908]
 [1799]
 [1914]
 [1603]
 [1782]
 [1980]
 [1228]
 [1838]
 [2006]
 [1953]
 [1846]
 [1903]
 [1470]
 [1774]
 [1599]
 [1446]
 [1324]
 [1054]
 [1952]
 [1928]
 [1997]
 [1764]
 [1943]
 [1932]
 [1615]
 [1428]
 [1036]
 [ 721]
 [1097]
 [1998]
 [1033]
 [1892]
 [1904]
 [1803]
 [1825]
 [1370]
 [1836]
 [1853]
 [1963]
 [1469]
 [1385]
 [ 246]
 [1987]
 [1153]
 [ 178]
 [1790]
 [1927]
 [1139]
 [1865]
 [1804]
 [1974]
 [1235]
 [1681]
 [1185]
 [2009]
 [1894]
 [1141]
 [1203]
 [1808]
 [1867]
 [1274]
 [1891]
 [1779]
 [1342]
 [1920]
 [ 851]
 [1994]
 [1975]
 [1979]
 [1880]
 [1647]
 [1365]
 [ 448]
 [1119]
 [1256]
 [1212]
 [1268]
 [1878]
 [1805]
 [1889]
 [1870]
 [1906]
 [1959]


In [10]:
matrix = data.flatten()
matrix = np.tile(matrix, (len(matrix), 1))
print(matrix)

[[1897 1850 1218 ...  219 1851 1955]
 [1897 1850 1218 ...  219 1851 1955]
 [1897 1850 1218 ...  219 1851 1955]
 ...
 [1897 1850 1218 ...  219 1851 1955]
 [1897 1850 1218 ...  219 1851 1955]
 [1897 1850 1218 ...  219 1851 1955]]


In [12]:
r = data + matrix
np.fill_diagonal(r, 0)
print(r)

[[   0 3747 3115 ... 2116 3748 3852]
 [3747    0 3068 ... 2069 3701 3805]
 [3115 3068    0 ... 1437 3069 3173]
 ...
 [2116 2069 1437 ...    0 2070 2174]
 [3748 3701 3069 ... 2070    0 3806]
 [3852 3805 3173 ... 2174 3806    0]]


In [17]:
print(np.where(r == 2020, data, 1).prod())

436404


In [20]:
i = np.where(r == 2020)
print(i)
print(data[i[0][0]])
print(data[i[0][1]])
print(data[i[0][0]] * data[i[0][1]])

(array([55, 83], dtype=int64), array([83, 55], dtype=int64))
[1774]
[246]
[436404]
