In [73]:
import numpy as np
import pandas as pd

In [74]:
df = pd.read_csv('2015_day6.csv', header=None, names=['instruction'], sep='\n')
df.head()

instruction
0    toggle 461,550 through 564,900
1   turn off 370,39 through 425,839
2  turn off 464,858 through 833,915
3  turn off 812,389 through 865,874
4   turn on 599,989 through 806,993

In [75]:
def get_corner1(i):
    return i.split(' through ')[0].split(' ')[-1].split(',')

def get_corner2(i):
    return i.split(' through ')[1].split(' ')[-1].split(',')

def get_action(i):
    if 'toggle' in i:
        return 'toggle'
    if 'off' in i:
        return 'off'
    if 'on' in i:
        return 'on'
    return None

In [76]:
df['corner1'] = df['instruction'].apply(get_corner1)
df['corner2'] = df['instruction'].apply(get_corner2)
df['action'] = df['instruction'].apply(get_action)
df.head()

instruction     corner1     corner2  action
0    toggle 461,550 through 564,900  [461, 550]  [564, 900]  toggle
1   turn off 370,39 through 425,839   [370, 39]  [425, 839]     off
2  turn off 464,858 through 833,915  [464, 858]  [833, 915]     off
3  turn off 812,389 through 865,874  [812, 389]  [865, 874]     off
4   turn on 599,989 through 806,993  [599, 989]  [806, 993]      on

In [77]:
grid = np.zeros((1000, 1000))
grid

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [78]:
c1 = df['corner1'].to_numpy()
c2 = df['corner2'].to_numpy()
a = df['action'].to_numpy()

In [79]:
for i in range(len(c1)):
    for x in range(int(c1[i][0]), int(c2[i][0]) + 1):
        for y in range(int(c1[i][1]), int(c2[i][1]) + 1):
            if a[i] == 'on':
                grid[x][y] = 1
            if a[i] == 'off':
                grid[x][y] = 0
            if a[i] == 'toggle':
                grid[x][y] = abs(grid[x][y] - 1)

In [80]:
print(grid.sum())
print(grid)

543903.0
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
