In [37]:
import numpy as np
from collections import defaultdict

In [38]:
with open('2023_day3.csv', 'r') as f:
    s = f.readlines()
s = [list(x.replace('\n','')) for x in s]
a = np.array(s)
print(a)

[['.' '.' '.' ... '.' '.' '.']
 ['.' '.' '.' ... '.' '.' '.']
 ['.' '2' '1' ... '.' '.' '.']
 ...
 ['.' '.' '.' ... '.' '.' '.']
 ['.' '.' '.' ... '.' '.' '.']
 ['.' '.' '.' ... '.' '.' '.']]


In [39]:
# symbol locations
f = np.where(a == '*', 1, 0)
f = f.astype(int)
i = 1
# number the gear locations to we tell which numbers share the same gear
for r in range(len(f)):
    for c in range(len(f[r])):
        if f[r, c] == 1:
            f[r, c] = i
            i += 1
print(f)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [40]:
# valid part num locations
h = f + np.roll(f, 1, axis=0) # down
h = h + np.roll(f, 1, axis=1) # right
h = h + np.roll(f, -1, axis=0) # up
h = h + np.roll(f, -1, axis=1) # left
h = h + np.roll(np.roll(f, 1, axis=0), -1, axis=1) # lower left
h = h + np.roll(np.roll(f, 1, axis=0), 1, axis=1) # lower right
h = h + np.roll(np.roll(f, -1, axis=0), -1, axis=1) # upper left
h = h + np.roll(np.roll(f, -1, axis=0), 1, axis=1) # upper right
h = np.where(h == 0, 0, h)
print(h)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [41]:
# number locations
# don't want to confuse actual zeroes with . or symbols so set to 10
n = np.where(a == '0', 10, a)
n = np.where(np.isin(a, [str(x) for x in range(10)]), n, 0)
n = n.astype(int)
print(n)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 2 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [42]:
# locations where a digit is valid part number because adjacent to symbol
v = h * n
print(v)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [43]:
# return actual zeroes from 10 to 0
nt = np.where(n == 0, -1, n)
nt = np.where(n == 10, 0, nt)
print(nt)

[[-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1  2  1 ... -1 -1 -1]
 ...
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]]


In [44]:
res = defaultdict(list)
valid = False
for r in range(len(nt)):
    # at the end of the row need to save number if valid, no . see row 113
    if valid:
        res[g].append(int(d))
    valid = False
    d = ''
    for c in range(len(nt[r])):
        # build numbers one char at a time
        # if you reach a valid point make sure you save it when done
        if v[r, c] > 0:
            valid = True
            g = h[r, c]
        if nt[r, c] >= 0:
            d += str(nt[r, c])
        else:
            # next character is . so take number and save it
            if valid:
                res[g].append(int(d))
            valid = False
            d = ''
print(res)

defaultdict(<class 'list'>, {1: [585, 210], 3: [30, 760], 2: [217, 616], 5: [447, 743], 6: [973, 535], 7: [639, 999], 4: [830, 949], 10: [794], 11: [373, 800], 8: [853], 12: [666, 956], 13: [807, 237], 9: [960, 186], 15: [725, 193], 14: [700, 818], 16: [906, 113], 18: [165, 984], 17: [610, 643], 19: [489, 795], 21: [915, 848], 22: [961, 201], 20: [277], 24: [993, 491], 25: [268, 978], 26: [429, 745], 28: [582, 400], 23: [538, 789], 29: [508, 69], 30: [250, 814], 27: [77, 957], 32: [653, 834], 33: [276, 821], 34: [571, 676], 31: [65], 35: [765, 789], 36: [758], 38: [227, 664], 39: [288, 407], 40: [226, 43], 42: [592], 43: [943, 405], 41: [575, 708], 37: [524], 44: [353, 96], 45: [781, 700], 46: [272, 897], 47: [769, 420], 48: [432, 121], 49: [887], 50: [802, 578], 51: [798, 764], 52: [456, 80], 53: [182, 637], 54: [816, 517], 56: [911, 801], 57: [990, 352], 55: [792, 576], 58: [657, 283], 59: [728, 422], 60: [446, 95], 61: [963, 617], 62: [201, 215], 64: [232], 65: [116, 730], 66: [630,

In [45]:
tot = 0
for l in res:
    if len(res[l]) == 2:
        tot += res[l][0] * res[l][1]
print(tot)

84399773
