In [9]:
import numpy as np

In [10]:
with open('2023_day3.csv', 'r') as f:
    s = f.readlines()
s = [list(x.replace('\n','')) for x in s]
a = np.array(s)
print(a)

[['.' '.' '.' ... '.' '.' '.']
 ['.' '.' '.' ... '.' '.' '.']
 ['.' '2' '1' ... '.' '.' '.']
 ...
 ['.' '.' '.' ... '.' '.' '.']
 ['.' '.' '.' ... '.' '.' '.']
 ['.' '.' '.' ... '.' '.' '.']]


In [11]:
# symbol locations
f = np.where(np.isin(a, [str(x) for x in range(10)]), 0, a)
f = np.where(f == '.', 0, f)
f = np.where(f != '0', 1, f)
f = f.astype(int)
print(f)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [12]:
# valid part num locations
h = f + np.roll(f, 1, axis=0) # down
h = h + np.roll(f, 1, axis=1) # right
h = h + np.roll(f, -1, axis=0) # up
h = h + np.roll(f, -1, axis=1) # left
h = h + np.roll(np.roll(f, 1, axis=0), -1, axis=1) # lower left
h = h + np.roll(np.roll(f, 1, axis=0), 1, axis=1) # lower right
h = h + np.roll(np.roll(f, -1, axis=0), -1, axis=1) # upper left
h = h + np.roll(np.roll(f, -1, axis=0), 1, axis=1) # upper right
h = np.where(h == 0, 0, 1)
print(h)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [13]:
# number locations
# don't want to confuse actual zeroes with . or symbols so set to 10
n = np.where(a == '0', 10, a)
n = np.where(np.isin(a, [str(x) for x in range(10)]), n, 0)
n = n.astype(int)
print(n)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 2 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [14]:
# locations where a digit is valid part number because adjacent to symbol
v = h * n
print(v)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [15]:
# return actual zeroes from 10 to 0
nt = np.where(n == 0, -1, n)
nt = np.where(n == 10, 0, nt)
print(nt)

[[-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1  2  1 ... -1 -1 -1]
 ...
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]]


In [16]:
res = []
valid = False
for r in range(len(nt)):
    # at the end of the row need to save number if valid, no . see row 113
    if valid:
        res.append(int(d))
    valid = False
    d = ''
    for c in range(len(nt[r])):
        # build numbers one char at a time
        # if you reach a valid point make sure you save it when done
        if v[r, c] > 0:
            valid = True
        if nt[r, c] >= 0:
            d += str(nt[r, c])
        else:
            # next character is . so take number at save
            if valid:
                res.append(int(d))
            valid = False
            d = ''
print(res)
print(sum(res))

[143, 425, 585, 30, 217, 616, 447, 973, 210, 639, 541, 830, 912, 743, 828, 671, 760, 737, 949, 568, 87, 535, 794, 616, 373, 999, 853, 666, 365, 807, 680, 800, 684, 960, 186, 725, 631, 700, 818, 402, 956, 237, 490, 998, 624, 600, 283, 906, 301, 495, 917, 165, 193, 977, 610, 489, 795, 545, 915, 641, 123, 113, 643, 117, 483, 961, 984, 878, 277, 80, 802, 591, 228, 848, 810, 740, 902, 201, 993, 268, 429, 582, 538, 789, 941, 136, 334, 508, 250, 745, 77, 653, 491, 192, 978, 26, 957, 400, 834, 85, 429, 291, 690, 69, 814, 276, 571, 65, 765, 179, 460, 577, 50, 758, 52, 821, 676, 227, 273, 789, 288, 226, 592, 943, 378, 876, 497, 575, 524, 353, 664, 781, 108, 124, 407, 272, 43, 421, 708, 405, 769, 432, 57, 887, 637, 96, 700, 573, 644, 802, 798, 897, 456, 130, 182, 420, 369, 121, 916, 637, 816, 911, 97, 990, 557, 355, 578, 764, 872, 80, 792, 517, 609, 675, 657, 728, 446, 963, 201, 232, 576, 116, 630, 801, 352, 422, 538, 435, 730, 952, 283, 931, 95, 617, 215, 174, 139, 375, 755, 426, 972, 82, 854, 2