In [88]:
import pandas as pd
import numpy as np

In [89]:
d = np.genfromtxt('2021_day11_sample.csv', delimiter=1)
d

array([[5., 4., 8., 3., 1., 4., 3., 2., 2., 3.],
       [2., 7., 4., 5., 8., 5., 4., 7., 1., 1.],
       [5., 2., 6., 4., 5., 5., 6., 1., 7., 3.],
       [6., 1., 4., 1., 3., 3., 6., 1., 4., 6.],
       [6., 3., 5., 7., 3., 8., 5., 4., 7., 8.],
       [4., 1., 6., 7., 5., 2., 4., 6., 4., 5.],
       [2., 1., 7., 6., 8., 4., 1., 7., 2., 1.],
       [6., 8., 8., 2., 8., 8., 1., 1., 3., 4.],
       [4., 8., 4., 6., 8., 4., 8., 5., 5., 4.],
       [5., 2., 8., 3., 7., 5., 1., 5., 2., 6.]])

In [90]:
d = np.genfromtxt('2021_day11.csv', delimiter=1)
n = d.copy()
n = np.pad(n, pad_width=1, mode='constant', constant_values=-1)
fc = 0
for x in range(100):
    n[np.where(n >= 0)] = n[np.where(n >= 0)] + 1
    # print(n)
    w = np.where(n >= 10)
    flashed = []
    to_flash = list(zip(w[0], w[1]))
    # print(to_flash)
    # print(n[2,1])
    while len(to_flash) > 0:
        i = to_flash.pop()
        flashed.append(i)
        fc += 1
        # print(to_flash)
        # print(i)
        
        u = n[i[0]-1, i[1]].sum()
        if u != -1:
            n[i[0]-1, i[1]] += 1
        d = n[i[0]+1, i[1]].sum()
        if d != -1:
            n[i[0]+1, i[1]] += 1
        l = n[i[0], i[1]-1].sum()
        if l != -1:
            n[i[0], i[1]-1] += 1
        r = n[i[0], i[1]+1].sum()
        if r != -1:
            n[i[0], i[1]+1] += 1
        nw = n[i[0]-1, i[1]-1].sum()
        if nw != -1:
            n[i[0]-1, i[1]-1] += 1
        ne = n[i[0]+1, i[1]-1].sum()
        if ne != -1:
            n[i[0]+1, i[1]-1] += 1
        sw = n[i[0]-1, i[1]+1].sum()
        if sw != -1:
           n[i[0]-1, i[1]+1] += 1 
        se = n[i[0]+1, i[1]+1].sum()
        if se != -1:
            n[i[0]+1, i[1]+1] += 1
        if n[i[0]-1, i[1]].sum() >= 10 and (i[0]-1, i[1]) not in to_flash + flashed:
            to_flash.append((i[0]-1, i[1]))
        if n[i[0]+1, i[1]].sum() >= 10 and (i[0]+1, i[1]) not in to_flash + flashed:
            to_flash.append((i[0]+1, i[1]))
        if n[i[0], i[1]-1].sum() >= 10 and (i[0], i[1]-1) not in to_flash + flashed:
            to_flash.append((i[0], i[1]-1))
        if n[i[0], i[1]+1].sum() >= 10 and (i[0], i[1]+1) not in to_flash + flashed:
            to_flash.append((i[0], i[1]+1))
        if n[i[0]-1, i[1]-1].sum() >= 10 and (i[0]-1, i[1]-1) not in to_flash + flashed:
            to_flash.append((i[0]-1, i[1]-1))
        if n[i[0]+1, i[1]-1].sum() >= 10 and (i[0]+1, i[1]-1) not in to_flash + flashed:
            to_flash.append((i[0]+1, i[1]-1))
        if n[i[0]-1, i[1]+1].sum() >= 10 and (i[0]-1, i[1]+1) not in to_flash + flashed:
            to_flash.append((i[0]-1, i[1]+1))
        if n[i[0]+1, i[1]+1].sum() >= 10 and (i[0]+1, i[1]+1) not in to_flash + flashed:
            to_flash.append((i[0]+1, i[1]+1))
        # break
    n[np.where(n >= 10)] = 0
print(n)
print(fc)
    # for i in range(1,len(n)):
    #     for j in range(1,len(n[0])):
    #         v = n[i-1:i,j-1:j].sum()
    #         u = n[i-2:i-1,j-1:j].sum()
    #         d = n[i:i+1,j-1:j].sum()
    #         l = n[i-1:i,j-2:j-1].sum()
    #         r = n[i-1:i,j:j+1].sum()
    #         print(u)

[[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1.  0.  7.  6.  8.  2.  2.  2.  2.  2.  6. -1.]
 [-1.  7.  7.  6.  9.  7.  2.  2.  2.  2.  2. -1.]
 [-1.  6.  6.  6.  9.  7.  3.  2.  2.  2.  2. -1.]
 [-1.  6.  6.  6.  9.  1.  3.  2.  2.  2.  2. -1.]
 [-1.  6.  6.  6.  9.  3.  3.  2.  2.  2.  2. -1.]
 [-1.  6.  6.  6.  9.  2.  2.  2.  2.  2.  2. -1.]
 [-1.  6.  6.  6.  9.  2.  2.  2.  2.  2.  2. -1.]
 [-1.  6.  6.  6.  9.  2.  2.  2.  2.  3.  3. -1.]
 [-1.  6.  6.  6.  8.  2.  2.  2.  3.  5.  0. -1.]
 [-1.  6.  6.  6.  7.  9.  2.  2.  3.  0.  0. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]]
1546
