In [41]:
import csv
import numpy as np
import pandas as pd
from random import shuffle

In [42]:
with open('2020_day10.csv', 'r') as f:
    r = csv.reader(f)
    s = [int(x[0]) for x in r]

In [43]:
s = sorted(s)

In [44]:
a = np.array([0] + s + [max(s) + 3])
print(a)

[  0   1   2   5   6   7   8   9  12  13  14  15  16  19  22  23  24  25
  26  29  30  31  32  35  36  37  38  41  44  45  46  47  50  51  52  53
  54  57  58  59  62  63  66  67  68  69  70  73  76  77  78  79  80  83
  86  89  90  91  94  95  96  97  98 101 104 107 108 109 110 113 114 115
 116 119 120 123 124 125 126 127 130 131 134 137 138 139 140 143 144 145
 148 149 150 151 154]


In [45]:
d = {}
for v in a:
    d[v] = list(np.extract(np.logical_and(a - v <= 3, a - v > 0), a))
print(d)

{0: [1, 2], 1: [2], 2: [5], 5: [6, 7, 8], 6: [7, 8, 9], 7: [8, 9], 8: [9], 9: [12], 12: [13, 14, 15], 13: [14, 15, 16], 14: [15, 16], 15: [16], 16: [19], 19: [22], 22: [23, 24, 25], 23: [24, 25, 26], 24: [25, 26], 25: [26], 26: [29], 29: [30, 31, 32], 30: [31, 32], 31: [32], 32: [35], 35: [36, 37, 38], 36: [37, 38], 37: [38], 38: [41], 41: [44], 44: [45, 46, 47], 45: [46, 47], 46: [47], 47: [50], 50: [51, 52, 53], 51: [52, 53, 54], 52: [53, 54], 53: [54], 54: [57], 57: [58, 59], 58: [59], 59: [62], 62: [63], 63: [66], 66: [67, 68, 69], 67: [68, 69, 70], 68: [69, 70], 69: [70], 70: [73], 73: [76], 76: [77, 78, 79], 77: [78, 79, 80], 78: [79, 80], 79: [80], 80: [83], 83: [86], 86: [89], 89: [90, 91], 90: [91], 91: [94], 94: [95, 96, 97], 95: [96, 97, 98], 96: [97, 98], 97: [98], 98: [101], 101: [104], 104: [107], 107: [108, 109, 110], 108: [109, 110], 109: [110], 110: [113], 113: [114, 115, 116], 114: [115, 116], 115: [116], 116: [119], 119: [120], 120: [123], 123: [124, 125, 126], 124: 

In [46]:
# too long
paths =[[0]]
completed = 0
while len(paths) > 0:
    p = paths.pop()
    if len(d[p[-1]]) == 0:
        completed += 1
        continue
    for n in d[p[-1]]:
        pn = p + [n]
        paths.append(pn)
print(completed)
# print(len(completed))

KeyboardInterrupt: 

In [47]:
print(completed)

197563113


In [17]:
comp = []
todo = [[0]]
t = 0
while len(todo) > 0:
    curr = todo.pop()
    v = curr[-1]
    i = np.where(a == v)[0][0]
    n = np.where(np.logical_and(a - a[i] <= 3, a - a[i] > 0))[0]
    if len(n) == 0:
        # comp.append(curr)
        t += 1
        continue
    for p in a[n]:
        todo.append(curr + [p])
    # print(v, i, n)
# for c in comp[::-1]:
#     print(c)
# print(len(comp))
print(t)

KeyboardInterrupt: 

In [18]:
print(todo)

[[0, 1], [0, 2, 5, 6], [0, 2, 5, 7], [0, 2, 5, 8, 9, 12, 13], [0, 2, 5, 8, 9, 12, 14], [0, 2, 5, 8, 9, 12, 15, 16, 19, 22, 23], [0, 2, 5, 8, 9, 12, 15, 16, 19, 22, 24], [0, 2, 5, 8, 9, 12, 15, 16, 19, 22, 25, 26, 29, 30], [0, 2, 5, 8, 9, 12, 15, 16, 19, 22, 25, 26, 29, 31, 32, 35, 36, 37], [0, 2, 5, 8, 9, 12, 15, 16, 19, 22, 25, 26, 29, 31, 32, 35, 36, 38, 41, 44, 45, 46], [0, 2, 5, 8, 9, 12, 15, 16, 19, 22, 25, 26, 29, 31, 32, 35, 36, 38, 41, 44, 45, 47, 50, 51], [0, 2, 5, 8, 9, 12, 15, 16, 19, 22, 25, 26, 29, 31, 32, 35, 36, 38, 41, 44, 45, 47, 50, 52, 53], [0, 2, 5, 8, 9, 12, 15, 16, 19, 22, 25, 26, 29, 31, 32, 35, 36, 38, 41, 44, 45, 47, 50, 52, 54, 57, 58], [0, 2, 5, 8, 9, 12, 15, 16, 19, 22, 25, 26, 29, 31, 32, 35, 36, 38, 41, 44, 45, 47, 50, 52, 54, 57, 59, 62, 63, 66, 67], [0, 2, 5, 8, 9, 12, 15, 16, 19, 22, 25, 26, 29, 31, 32, 35, 36, 38, 41, 44, 45, 47, 50, 52, 54, 57, 59, 62, 63, 66, 68, 69, 70, 73, 76, 77, 78], [0, 2, 5, 8, 9, 12, 15, 16, 19, 22, 25, 26, 29, 31, 32, 35, 36,

In [18]:
paths = []
for x in range(100000):
    i = 0
    p = []
    v = np.where(np.logical_and(a - a[i] <= 3, a - a[i] > 0))[0]
    while len(v) > 0:
        p.append(a[i])
        shuffle(v)
        i = v[0]
        v = np.where(np.logical_and(a - a[i] <= 3, a - a[i] > 0))[0]
    if p not in paths:
        paths.append(p)
print(len(paths))
    

15208


In [121]:
print([] + [1])

[1]


In [136]:
tot = 0
level = [0]
while len(level) > 0:
    # print(level)
    new_level = []
    for i in level:
        # print(a[np.where(np.logical_and(a - i <= 3, a - i > 0))[0]])
        # print(new_level)
        new_level += list(a[np.where(np.logical_and(a - i <= 3, a - i > 0))[0]])
        # print(new_level)
    level = new_level
    tot = max(len(level), tot)
print(tot)

12419


In [113]:
# paths = np.array([[0]])
tot = 1
branches = []
for i in range(len(a)-1):
    v = np.where(np.logical_and(a - a[i] <= 3, a - a[i] > 0))[0]
    if len(v) > 1:
        branches.append([a[i], len(a[v]), a[v]])
    print(a[i], len(a[v]), a[v])

# # print(branches)
# bid = {x[0]:x[1] for x in branches}
# last =[0, 0, []]
# t = 1
# for b in branches:
#     print(t, b)
#     if last[0] in b[2]:
#         t *= b[1] - 1
#     else:
#         t *= b[1]
#     # t = t * (b[1] - len(list(set(b[2]) & set(last[2])))+1)
#     # if b[0] in last[2]:
#     #     t = t * (last[1] - 1)
#     # else:
#     #     t = t * b[1]
#     last = b
# print(t)
# print(branches)
# bi = [x[0] for x in branches]
# bid = {x[0]:x[1] for x in branches}
# ba = {x[0]:x[2] for x in branches}
# for b in branches:
#     for b2 in branches:
#        if b[0] in b2[2]:
#            bid[b2[0]] -= 1
#         #    bid[b2[0]] = 0
# t = 1
# for p in bid.values():
#     t *= p
# # print(prod(bid.values())) 
# print(bid)
# print(t)



0 1 [1]
1 1 [4]
4 3 [5 6 7]
5 2 [6 7]
6 1 [7]
7 1 [10]
10 2 [11 12]
11 1 [12]
12 1 [15]
15 1 [16]
16 1 [19]
19 1 [22]


In [143]:
diffs = np.array(np.meshgrid([1, 2, 3], [1,2,3], [1,2,3], [1,2,3], [1,2,3], [1,2,3], [0])).T.reshape(-1,7)
print(diffs)

[[1 1 1 ... 1 1 0]
 [1 2 1 ... 1 1 0]
 [1 3 1 ... 1 1 0]
 ...
 [3 1 3 ... 3 3 0]
 [3 2 3 ... 3 3 0]
 [3 3 3 ... 3 3 0]]


In [153]:
l = [[1,2,3]]*(len(a)-1) + [[0]]
print(l)
diffs = np.array(np.meshgrid(*l)).T.reshape(-1,len(a))
print(diffs)

[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [0]]
[[1 1 1 ... 1 1 0]
 [1 2 1 ... 1 1 0]
 [1 3 1 ... 1 1 0]
 ...
 [3 1 3 ... 3 3 0]
 [3 2 3 ... 3 3 0]
 [3 3 3 ... 3 3 0]]


In [155]:
c = 0
for d in diffs:
    t = a + d
    if np.where(np.in1d(t, a))[0]
        c += 1
print(c)

AxisError: axis 1 is out of bounds for array of dimension 1

In [163]:
diffs = [1,3,1,1,1,3,0]
# diffs = np.array([3] * (len(a) - 1) + [0])
print(a)
print(diffs)
t = a + diffs
print(t)
print(a[1:])
print(t[:-1])
print((a[1:] == t[:-1]).all())
print(np.where(np.in1d(t[:-1], a[1:]))[0])



[ 0  1  4  5  6  7 10]
[1, 3, 1, 1, 1, 3, 0]
[ 1  4  5  6  7 10 10]
[ 1  4  5  6  7 10]
[ 1  4  5  6  7 10]
True
[0 1 2 3 4 5]


In [89]:
paths = np.array([[0]])
print(paths)

[[0]]
